apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
        - name: app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 9000
          env:
            - name: APP_ENV
              value: {{ .Values.env.APP_ENV }}
            - name: DB_HOST
              value: {{ .Values.env.DB_HOST }}
            - name: DB_DATABASE
              value: {{ .Values.env.DB_DATABASE }}
            - name: DB_USERNAME
              value: {{ .Values.env.DB_USERNAME }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: DB_PASSWORD
            - name: SESSION_DRIVER
              value: {{ .Values.env.SESSION_DRIVER }}