apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: default
type: Opaque
data:
  DB_PASSWORD: c2VjcmV0        # base64("secret")
  DB_ROOT_PASSWORD: cm9vdA==    # base64("root")
