#version: '3.9'

services:
  app:
    build:
      context: ./laravel-job-runner
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./laravel-job-runner:/var/www
    environment:
      APP_ENV: local
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: user
      DB_PASSWORD: secret
      SESSION_DRIVER: file
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravel
    expose:
      - "9000"

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "8001:80"
    volumes:
      - ./laravel-job-runner:/var/www
      - ./laravel-job-runner/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  worker:
    build:
      context: ./laravel-job-runner
      dockerfile: docker/worker/Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./laravel-job-runner:/var/www
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravel

  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  laravel:

volumes:
  dbdata:
