services:
  app:
    build:
      context: ./laravel-job-runner
      dockerfile: docker/php/Dockerfile
    container_name: laravel-app
    environment:
      APP_ENV: production
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: user
      DB_PASSWORD: secret
    volumes:
      - ./laravel-job-runner:/var/www
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./laravel-job-runner:/var/www
      - ./laravel-job-runner/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  worker:
    build:
      context: ./laravel-job-runner
      dockerfile: docker/worker/Dockerfile
    container_name: laravel-worker
    depends_on:
      - app
    volumes:
      - ./laravel-job-runner:/var/www
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel-db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
