#version: '3.9'

services:
  app:
    image: custom-laravel-job-runner-app
    build:
      context: ./laravel-job-runner
      dockerfile: docker/php/Dockerfile
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      APP_ENV: production
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: user
      DB_PASSWORD: secret
      SESSION_DRIVER: file
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./laravel-job-runner:/var/www
      - ./laravel-job-runner/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - laravel

  worker:
    image: custom-laravel-job-runner-worker
    build:
      context: ./laravel-job-runner
      dockerfile: docker/worker/Dockerfile
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - laravel

  db:
    image: mysql:8.0
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
