services:
  app:
    build:
      context: ./laravel-job-runner
      dockerfile: docker/Dockerfile.runner
    ports:
      - "80:8000"
    command: |
      sh -c "php artisan migrate --force && php artisan config:cache && php artisan serve --host=0.0.0.0 --port=8000"
    environment:
      APP_ENV: production
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: user
      DB_PASSWORD: secret

  worker:
    build:
      context: ./laravel-job-runner
      dockerfile: docker/worker/Dockerfile
    command: php worker/worker.php
    environment:
      APP_ENV: production
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: user
      DB_PASSWORD: secret
