apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
  namespace: default
type: Opaque
data:
  DB_PASSWORD: c2VjcmV0        # base64 for "secret"
  DB_ROOT_PASSWORD: cm9vdA==    # base64 for "root"
