# Kubernetes Laravel Job Runner Stack

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
        - name: app
          image: custom-laravel-job-runner-app:latest
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: laravel-config
            - secretRef:
                name: laravel-secret
          volumeMounts:
            - name: storage
              mountPath: /var/www/storage
      volumes:
        - name: storage
          emptyDir: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel-worker
  template:
    metadata:
      labels:
        app: laravel-worker
    spec:
      containers:
        - name: worker
          image: custom-laravel-job-runner-worker:latest
          command: ["php", "worker/worker.php"]
          envFrom:
            - configMapRef:
                name: laravel-config
            - secretRef:
                name: laravel-secret

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-mysql
spec:
  selector:
    matchLabels:
      app: laravel-mysql
  template:
    metadata:
      labels:
        app: laravel-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: laravel
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: laravel-secret
                  key: DB_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: laravel-secret
                  key: DB_ROOT_PASSWORD
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          emptyDir: {}
